# meshing settings
mesh:
  size_factor: 1  # use this to change mesh size globally
  order: 1  # 2nd order is better if you want to evaluate heat fluxes

# geometry parameters

melt:
  h: 0.03
  r: 0.05
  mesh_size: 0.0025
  T_init: 506
  material: tin-liquid

crucible:
  h: 0.05  # drawing
  h_in: 0.04
  r_in: 0.05  # drawing
  r_out: 0.06  # drawing
  t_bt: 0.01  # drawing
  mesh_size: 0.0025
  T_init: 520
  material: graphite-CZ3R6300
  
crystal:
  r: 0.004
  h: 0.1
  mesh_size: 0.00125
  material: tin-solid
  T_init: 293.15 

crucible_adapter:
  r_in: 0.01  # drawing
  h: 0.045
  r_out: 0.06  # drawing
  t_bt: 0.055
  mesh_size: 0.0025
  T_init: 313.15
  material: graphite-CZ3R6300


axis_bt:
  r_in: 0.0075  # measured
  r_out: 0.02  # measured
  h: 0.029 # variable
  t_bt: 0.069
  mesh_size: 0.0025
  T_init: 323.15
  material: steel-1.4541

seed:
  r: 0.0009  # estimated
  h: 0.04  # estimated
  mesh_size: 0.0025
  T_init: 420
  material: tin-solid

axis_top:
  r: 0.01  # measured
  t: 0.17
  h: 0.144
  mesh_size: 0.0025
  T_init: 303.15
  material: steel-1.4541

inductor:
  d: 0.01  # construction
  d_in: 0.008  # construction
  g: 0.006  # averaged
  n: 3
  X0: [0.075, -0.005]  # measured
  T_init: 293.15
  material: copper-inductor

vessel:
  r_in: 0.1315
  h_in: 0.383
  w: 0.005
  t: 0.069
  mesh_size: 0.0025
  T_init: 293.15
  material: steel-1.4541

atmosphere: 
  r: 0.3
  h: 0.5
  t: 0.135 
  T_init: 293.15
  material: air
  mesh_size: 0.035 