
general:
  heat_control: True

heating_induction:
  frequency: 13.5e+3  # Hz
  current: 100 # A

boundaries:
  inductor_inside:
    T: 293.15
  container_outside:
    T: 293.15

smart-heater:
  T: 505 
  control-point: False  # if False: use T at melt-crystal interface (triple point)
  x: 0.006
  y: 0.042
  z: 0.0



