# setup for Elmer simulation / solvers

axisymmetric_steady:
  Max Output Level: 4
  Coordinate System: Axi Symmetric
  Simulation Type: Steady state
  Steady State Max Iterations: 10
  Output File: case.result
  Output Intervals: 0

HeatSolver:
  Equation: 'Heat Equation'
  Procedure: '"HeatSolve" "HeatSolver"'
  Variable: '"Temperature"'
  Variable Dofs: 1
  Calculate Loads: True
  Exec Solver: Always
  Nonlinear System Convergence Tolerance: 1.0e-5
  Nonlinear System Max Iterations: 1000
  Nonlinear System Relaxation Factor: 0.7
  Steady State Convergence Tolerance: 1.0e-6
  Stabilize: True  # Necessary in convection-dominated systems (models manual p.17) --> decreases simulation duration
  Optimize Bandwidth: True
  Linear System Solver: Iterative  
  Linear System Iterative Method: BiCGStab
  Linear System Max Iterations: 10000
  Linear System Preconditioning: ILU
  Linear System Precondition Recompute: 1
  Linear System Convergence Tolerance: 1.0e-09
  Linear System Abort Not Converged: True
  Linear System Residual Output: 1
  Smart Heater Control After Tolerance: 1.0e-2

MagnetoDynamics2DHarmonic:
  Equation: MgDyn2DHarmonic
  Procedure: '"MagnetoDynamics2D" "MagnetoDynamics2DHarmonic"'
  Variable: 'Potential[Potential Re:1 Potential Im:1]'
  Variable Dofs: 2
  Exec Solver: Always
  Nonlinear System Convergence Tolerance: 1.0e-5
  Nonlinear System Max Iterations: 1000
  Nonlinear System Relaxation Factor: 0.7
  Steady State Convergence Tolerance: 1.0e-6
  Stabilize: True
  Optimize Bandwidth: True
  Linear System Solver: Iterative  
  Linear System Iterative Method: BiCGStab
  Linear System Max Iterations: 1000
  Linear System Preconditioning: ILU
  Linear System Precondition Recompute: 1
  Linear System Convergence Tolerance: 1.0e-7
  Linear System Abort Not Converged: True
  Linear System Residual Output: 1

MagnetoDynamicsCalcFields:
  Equation: CalcFields
  Procedure: '"MagnetoDynamics" "MagnetoDynamicsCalcFields"'
  Potential Variable: Potential
  Calculate Joule Heating: True
  Calculate Magnetic Field Strength: True
  Calculate Electric Field: True
  Calculate Current Density: True
  Calculate JxB: Logical True  
  Exec Solver: Always
  Calculate Nodal Fields: Logical False
  Calculate Elemental Fields: Logical True



ResultOutputSolver:
  Exec Solver: 'after saving'
  Equation: '"ResultOutput"'
  Procedure: '"ResultOutputSolve" "ResultOutputSolver"'
  VTU Format: True
  Save Geometry Ids: 'Logical True'

SteadyPhaseChange:
  Equation: PhaseSurface
  Variable: '"PhaseSurface"'
  Procedure: '"SteadyPhaseChange" "SteadyPhaseChange"'
  # Internal Mesh Movement: 'Logical True'
MeshUpdate:
  Equation: Mesh Update
  Linear System Solver: Iterative
  Linear System Iterative Method: BiCGStab
  Linear System Preconditioning: ILU1
  Linear System Max Iterations: 10000
  Linear System Convergence Tolerance: 1.0e-9
  Linear System Residual Output: 1
  Steady State Convergence Tolerance: 1.0e-6

SaveLine:
  Exec Solver: 'after all'
  Equation: '"SaveLine"'
  Procedure: '"SaveData" "SaveLine"'
  Filename: '"phase-if.dat"'
  Output Directory: './results'
  Variable 1: Temperature