# setup for Elmer simulation / solvers

axisymmetric_steady:
  Max Output Level: 4
  Coordinate System: Axi Symmetric
  Simulation Type: Steady state
  Steady State Max Iterations: 5
  Output File: case.result
  Output Intervals: 0



HeatSolver:
  Equation: 'Heat Equation'
  Procedure: '"HeatSolve" "HeatSolver"'
  Variable: '"Temperature"'
  Variable Dofs: 1
  Calculate Loads: True
  Exec Solver: Always
  Nonlinear System Convergence Tolerance: 1.0e-5
  Nonlinear System Max Iterations: 1000
  Nonlinear System Relaxation Factor: 0.7
  Steady State Convergence Tolerance: 1.0e-6
  Stabilize: True  # Necessary in convection-dominated systems (models manual p.17) --> decreases simulation duration
  Optimize Bandwidth: True
  Linear System Solver: Iterative  
  Linear System Iterative Method: BiCGStab
  Linear System Max Iterations: 10000
  Linear System Preconditioning: ILU
  Linear System Precondition Recompute: 1
  Linear System Convergence Tolerance: 1.0e-09
  Linear System Abort Not Converged: True
  Linear System Residual Output: 1
  Smart Heater Control After Tolerance: 1.0e-2

Navier-Stokes:
  Exec Solver : Always
  Equation : 'Navier-Stokes'
  Procedure : '"FlowSolve" "FlowSolver"'
  Variable : 'Flow Solution[Velocity:2 Pressure:1]'
  Stabilize : True
  Steady State Convergence Tolerance : 0.001
  Nonlinear System Convergence Tolerance : 1.0e-6
  Nonlinear System Max Iterations : 100
  Nonlinear System Newton After Iterations : 3
  Nonlinear System Newton After Tolerance : 1.0e-3
  Nonlinear System Relaxation Factor : 0.5
  Linear System Solver : Iterative
  Linear System Iterative Method : BiCGStabL
  BiCgStabl Polynomial Degree : 4
  Linear System Max Iterations : 500
  Linear System Convergence Tolerance : 1.0e-8
  Linear System Preconditioning : ILU0
  Linear System ILUT Tolerance : 1.0e-3
  Linear System Abort Not Converged : True
  Linear System Residual Output : 1
  Linear System Precondition Recompute : 1

Navier-Stokes_M:
  Exec Solver : Always
  Equation : 'Navier-StokesM'
  Procedure : '"FlowSolve" "FlowSolver"'
  Variable : 'Flow SolutionM[VelocityM:2 PressureM:1]'
  Stabilize : True
  Steady State Convergence Tolerance : 0.001
  Nonlinear System Convergence Tolerance : 1.0e-6
  Nonlinear System Max Iterations : 100
  Nonlinear System Newton After Iterations : 3
  Nonlinear System Newton After Tolerance : 1.0e-3
  Nonlinear System Relaxation Factor : 0.5
  Linear System Solver : Iterative
  Linear System Iterative Method : BiCGStabL
  BiCgStabl Polynomial Degree : 4
  Linear System Max Iterations : 500
  Linear System Convergence Tolerance : 1.0e-8
  Linear System Preconditioning : ILU0
  Linear System ILUT Tolerance : 1.0e-3
  Linear System Abort Not Converged : True
  Linear System Residual Output : 1
  Linear System Precondition Recompute : 1

MagnetoDynamics2DHarmonic:
  Exec Solver: Before all
  Equation: MgDyn2DHarmonic
  Procedure: '"MagnetoDynamics2D" "MagnetoDynamics2DHarmonic"'
  Variable: 'Potential[Potential Re:1 Potential Im:1]'
  Variable Dofs: 2
  Nonlinear System Max Iterations : 3
  Nonlinear System Convergence Tolerance :  1.0e-6
  Nonlinear System Relaxation Factor :  1
  Steady State Convergence Tolerance: 1.0e-6
  Stabilize: True
  Optimize Bandwidth: True
  Linear System Solver  :  Iterative
  Linear System Symmetric : True
  Linear System Convergence Tolerance  :  1.e-10
  Linear System Max Iterations : 1000
  Linear System Residual Output : 10
  Linear System Abort not Converged : False
  Linear System preconditioning : ilu
  Linear System ILUT Tolerance : 1e-8
  Linear System Iterative Method  :  BicgstabL

MagnetoDynamicsCalcFields:
  Exec Solver : Before all
  Equation : CalcFields
  Procedure: '"MagnetoDynamics" "MagnetoDynamicsCalcFields"'
  Calculate Elemental Fields : Logical False
  Calculate Nodal Fields : Logical True
  Calculate Current Density : Logical True
  Calculate Joule Heating : Logical True
  Calculate JxB : Logical True  
  Linear System Solver : Iterative
  Linear System Symmetric: True
  Linear System Convergence Tolerance : 1.e-10
  Linear System Max Iterations: 1000
  Linear System Residual Output: 10
  Linear System Abort not Converged: False
  Linear System preconditioning: ilu
  Linear System ILUT Tolerance: 1e-8
  Linear System Iterative Method : BicgstabL
  Nonlinear System Max Iterations : 3

Elasticity:
  Exec Solver : Always
  Equation : Linear elasticity
  Procedure : '"StressSolve" "StressSolver"'
  Variable : '"Displacement"'
  Variable DOFs : Integer 2
  #! hierarchial p-element base (alternative for higher-order)
  Element : p:3
  Displace Mesh : Logical False
  Calculate Stresses : Logical True
  Linear System Solver : Direct
  Linear System Symmetric : Logical True
  Linear System Scaling : Logical False
  Linear System Iterative Method : BiCGStab
  Linear System Direct Method : UMFPACK
  Linear System Convergence Tolerance : 1.0e-8
  Linear System Max Iterations : 200
  Linear System Preconditioning : ILU2
  Nonlinear System Convergence Tolerance : Real 1.0e-7
  Nonlinear System Max Iterations : Integer 3
  Nonlinear System Relaxation Factor : Real 1
  Steady State Convergence Tolerance: 1.0e-6
  Optimize Bandwidth : True

ResultOutputSolver:
  Exec Solver: 'after saving'
  Equation: '"ResultOutput"'
  Procedure: '"ResultOutputSolve" "ResultOutputSolver"'
  VTU Format : Logical True
  Save Geometry Ids : Logical True
  Ascii Output : Logical True
  Show Variables : Logical True

save_scalars:
  Exec Solver: 'after saving'
  Equation: SaveScalars
  Procedure: '"SaveData" "SaveScalars"'
  Filename: '"scalars.dat"'
  Output Directory: './results'
  
  Operator 1 : 'diffusive flux'
  Variable 1 : 'Temperature'
  Coefficient 1 : 'Heat Conductivity'