# setup for Elmer simulation / solvers

# Evrything at pyelmer/examples


axisymmetric_steady:
  Max Output Level: 4
  Coordinate System: Axi Symmetric
  Simulation Type: Steady state
  Steady State Max Iterations: 5
  Output File: case.result
  Output Intervals: 0

# HeatSolver:
#   Exec Solver : Always
#   Equation : HeatSolver
#   Procedure: '"HeatSolve" "HeatSolver"'
#   Variable: '"Temperature"'
#   Variable Dofs : 1
#   Calculate Loads : True
#   Viewfactor combine elements : Logical True
#   Update View Factors : Logical False
#   Calculate Loads : Logical True  
#   Steady State Convergence Tolerance : 1e-06
#   Smart Heater Control After Tolerance : 0.0001
#   Stabilize : True
#   Optimize Bandwidth : True
#   Nonlinear System Convergence Tolerance : 1e-06
#   Nonlinear System Max Iterations : 100
#   Nonlinear System Relaxation Factor : 0.7
#   Linear System Solver : Iterative
#   Linear System Iterative Method : BiCGStab
#   Linear System Max Iterations : 1000
#   Linear System Preconditioning : ILU
#   Linear System Precondition Recompute : 1
#   Linear System Convergence Tolerance : 1e-08
#   Linear System Abort Not Converged : True
#   Linear System Residual Output : 1

HeatSolver:
  Equation: 'Heat Equation'
  Procedure: '"HeatSolve" "HeatSolver"'
  Variable: '"Temperature"'
  Variable Dofs: 1
  Calculate Loads: True
  Exec Solver: Always
  Nonlinear System Convergence Tolerance: 1.0e-5
  Nonlinear System Max Iterations: 1000
  Nonlinear System Relaxation Factor: 0.7
  Steady State Convergence Tolerance: 1.0e-6
  Stabilize: True  # Necessary in convection-dominated systems (models manual p.17) --> decreases simulation duration
  Optimize Bandwidth: True
  Linear System Solver: Iterative  
  Linear System Iterative Method: BiCGStab
  Linear System Max Iterations: 10000
  Linear System Preconditioning: ILU
  Linear System Precondition Recompute: 1
  Linear System Convergence Tolerance: 1.0e-09
  Linear System Abort Not Converged: True
  Linear System Residual Output: 1
  Smart Heater Control After Tolerance: 1.0e-2



MagnetoDynamics2DHarmonic:
  Exec Solver: Before all
  Equation: MgDyn2DHarmonic
  Procedure: '"MagnetoDynamics2D" "MagnetoDynamics2DHarmonic"'
  Variable: 'Potential[Potential Re:1 Potential Im:1]'
  Variable Dofs: 2
  
  Nonlinear System Max Iterations : 3
  Nonlinear System Convergence Tolerance :  1.0e-6
  Nonlinear System Relaxation Factor :  1
  Steady State Convergence Tolerance: 1.0e-6
  Stabilize: True
  Optimize Bandwidth: True

  Linear System Solver  :  Iterative
  Linear System Symmetric : True
  Linear System Convergence Tolerance  :  1.e-10
  Linear System Max Iterations : 1000
  Linear System Residual Output : 10
  Linear System Abort not Converged : False
  Linear System preconditioning : ilu
  Linear System ILUT Tolerance : 1e-8
  Linear System Iterative Method  :  BicgstabL



MagnetoDynamicsCalcFields:
  Exec Solver : Before all
  Equation : CalcFields
  Procedure: '"MagnetoDynamics" "MagnetoDynamicsCalcFields"'
  Calculate Elemental Fields : Logical False
  Calculate Nodal Fields : Logical True
  Calculate Current Density : Logical True
  Calculate Joule Heating : Logical True
  Calculate JxB : Logical True  
  Linear System Solver : Iterative
  Linear System Symmetric: True
  Linear System Convergence Tolerance : 1.e-10
  Linear System Max Iterations: 1000
  Linear System Residual Output: 10
  Linear System Abort not Converged: False
  Linear System preconditioning: ilu
  Linear System ILUT Tolerance: 1e-8
  Linear System Iterative Method : BicgstabL
  Nonlinear System Max Iterations : 3


Elasticity:
  Exec Solver : Always
  Equation : Linear elasticity
  Procedure : '"StressSolve" "StressSolver"'
  Variable : '"Displacement"'
  Variable DOFs : Integer 2
  #! hierarchial p-element base (alternative for higher-order)
  Element : p:3

  Displace Mesh : Logical False
  Calculate Stresses : Logical True

  Linear System Solver : Direct
  Linear System Symmetric : Logical True
  Linear System Scaling : Logical False
  Linear System Iterative Method : BiCGStab
  Linear System Direct Method : UMFPACK
  Linear System Convergence Tolerance : 1.0e-8
  Linear System Max Iterations : 200
  Linear System Preconditioning : ILU2

  Nonlinear System Convergence Tolerance : Real 1.0e-7
  Nonlinear System Max Iterations : Integer 3
  Nonlinear System Relaxation Factor : Real 1

  Steady State Convergence Tolerance: 1.0e-6
  Optimize Bandwidth : True



ResultOutputSolver:
  Exec Solver: 'after saving'
  Equation: '"ResultOutput"'
  Procedure: '"ResultOutputSolve" "ResultOutputSolver"'
  VTU Format : Logical True
  Save Geometry Ids : Logical True
  Ascii Output : Logical True
  Show Variables : Logical True

SteadyPhaseChange:
  Equation: PhaseSurface
  Variable: '"PhaseSurface"'
  Procedure: '"SteadyPhaseChange" "SteadyPhaseChange"'
  # Internal Mesh Movement: 'Logical True'

MeshUpdate:
  Equation: Mesh Update
  Linear System Solver: Iterative
  Linear System Iterative Method: BiCGStab
  Linear System Preconditioning: ILU1
  Linear System Max Iterations: 10000
  Linear System Convergence Tolerance: 1.0e-9
  Linear System Residual Output: 1
  Steady State Convergence Tolerance: 1.0e-6


SaveLine:
  Exec Solver: 'after all'
  Equation: '"SaveLine"'
  Procedure: '"SaveData" "SaveLine"'
  Filename: '"phase-if.dat"'
  Output Directory: './results'
  Variable 1: Temperature

